### ISSUE TITLE
temporary disk usage compared to Entwine/EPT (but low mem use)

### ISSUE THREAD

**Issue by julienlau** [hobu/untwine#102] opened 2022-01-14 16:44 UTC
Hi,
I did some comparison of untinwe/copc (option single file) versus entwine/ept on various size of points.
It seems to me that untwine does not rely much on memory compared to entwine that can sometime crash due to memory overflow (not experience myself during the tests).
It seems that one tool does caching in memory and the other one does caching to disk.
This is nice to relieve memory pressure to a minimum (below 1GB) for untwine, but that could bite in case disk performance are bad.
Is that an optimization to run it on AWS lambda ?

On the other hand it seems that untwine rely much more on temporary files written to disks.
Is it normal ?
Will it change in the future ?

![image](https://user-images.githubusercontent.com/6950247/149552374-c75629a2-ca78-46eb-8677-f08205e56f82.png)

**Comment by hobu** [comment] 2022-01-14 16:46
> On the other hand it seems that untwine rely much more on temporary files written to disks.
Is it normal ?
Will it change in the future ?

[TANSTAAFL](https://en.wikipedia.org/wiki/There_ain%27t_no_such_thing_as_a_free_lunch)

This is by design. Entwine is a top-down tree builder and Untwine is a bottom-up builder. Maybe the naming hints at these different behaviors 😄 

Closing as there's no bug here.

**Closed by hobu** 2022-01-14 16:46 UTC

**Comment by abellgithub** [comment] 2022-01-14 18:09
You can reduce disk use with Untwine if you select only those dimensions that you care about with the `--dims` option. It also makes it run faster.
