### ISSUE TITLE
bu fails if output directory does not exist

### ISSUE THREAD

**Issue by wonder-sk** [hobu/untwine#3] opened 2020-11-05 21:29 UTC
When `bu` is run with an output directory that does not exist, it will abort:
```
terminate called after throwing an instance of 'pdalboost::filesystem::filesystem_error'
  what():  pdalboost::filesystem::create_directory: No such file or directory: "/tmp/bu/ept-data"
Aborted (core dumped)
```
Ideally it should auto-create the output directory.

**Comment by abellgithub** [comment] 2020-11-06 13:21
This was by design, but can be changed.

**Comment by abellgithub** [comment] 2020-11-06 16:42
Fixed in 0a8fab68964906976a56563bd83f1269f3893bc4

**Comment by abellgithub** [comment] 2020-12-08 23:32
Seems to me like something the user can and should deal with.

**Closed** 2022-01-24 17:22 UTC
